### ISSUE TITLE
登陆时需要验证码

### ISSUE THREAD

**Issue by letitfly** [kikyous/xfdown#20]
QQ：xxxx
PASSWD: 
请输入验证码：
vf # xprop:  unable to open display ''
Error: no "view" rule for type "image/jpeg" passed its test case
       (for more information, add "--debug=1" on the command line)

**Comment by kikyous** [comment]
你在tty里面吗？

**Comment by letitfly** [comment]
是的，运行的是python xfdown.py。我用的是Mac。
我猜QQ有时会弹出一个验证码窗口并要求你手工输入，能不能截获这个验证码图片，存储到本地，用户可以输入验证码进行下去？

**Comment by letitfly** [comment]
我看了一下code，发现你已经把验证码写到文件verify.jpg，但是程序运行时xdg-open没有弹出。
看来是因为我用ssh的缘故。
