### ISSUE TITLE
HTTP Error 502

### ISSUE THREAD

**Issue by huyinjie** [kikyous/xfdown#36]
貌似现在WebQQ协议不能用了？

**Comment by petronny** [comment]
这个貌似把默认的`page=0, limit=500`改成`page=0, limit=200`就好了
`limit=200`现在是默认值

**Comment by ryzzn** [comment]
![image](https://cloud.githubusercontent.com/assets/431968/5448419/9afded62-851a-11e4-8728-46d3e3a6d060.png)

handler的url貌似在我这里被改了。你可以试下这样可以不。我改了以后没问题。
