### ISSUE TITLE
离线任务列表用白色背景不合适

### ISSUE THREAD

**Issue by SimonFu** [kikyous/xfdown#6]
很多shell是黑底白字，这样任务列表将会看不到字，建议要么不加背景颜色，要么获取shell的背景颜色，然后再选择颜色作为背景！
建议选择前者，简单容易实现！

**Comment by SimonFu** [comment]
这个我的目前解决方法，是把背景颜色的那几行注释掉了！我觉得没什么问题，我要求也不高！

**Comment by kikyous** [comment]
嗯，我看看
